### ISSUE TITLE
request: add frame timestamps to output

### ISSUE THREAD

**Issue by wimdecorte** [sergio11/vehicle_detection_tracker#4]
In case I need to send the frame to another APi for better VMMR detection I'd like to see the frame's timestamps included for each vehicle.  Possibly just the one for the highest confidence of detection.

**Comment by sergio11** [comment]
Hi @wimdecorte 

Thanks for reporting this issue

I could add a new field to the output called `vehicle_frame_timestamp` which would be the same frame timestamp you provided

**Comment by sergio11** [comment]
Implemented in version [0.0.32](https://pypi.org/project/VehicleDetectionTracker/)
